version: '3.7'

services:
  db:
    container_name: database
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pnp
      - MYSQL_USER=pnp
      - MYSQL_PASSWORD=pnp
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  database: