version: '3.7'

services:
  db:
    container_name: database
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pnp
      - MYSQL_USER=pnp
      - MYSQL_PASSWORD=pnp
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

volumes:
  database:
